# Generated by Django 5.2.8 on 2025-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Patient allergies'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_illnesses',
            field=models.TextField(blank=True, help_text='Past medical conditions and illnesses'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('IN', 'In-Patient'), ('OUT', 'Out-Patient')], default='OUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='General medical notes'),
        ),
    ]
