# Generated by Django 5.2.8 on 2025-11-23 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_appointment_options_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment file paths/URLs'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Scheduled follow-up date', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_required',
            field=models.BooleanField(default=False, help_text='Does patient need follow-up?'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the visit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_notes',
            field=models.TextField(default='', help_text='Detailed notes from the visit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(help_text='Diagnosis details'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='lab_results',
            field=models.TextField(blank=True, help_text='Laboratory test results'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescriptions',
            field=models.TextField(help_text='Prescribed medications and dosage'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', '-visit_date'], name='hospital_me_patient_c307c4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['doctor', '-visit_date'], name='hospital_me_doctor__4a9557_idx'),
        ),
    ]
